// src/components/AISummary/TrialSummaryCard.jsx
// AI-generated plain language summary of a clinical trial

import React, { useState } from "react";

export default function TrialSummaryCard({ trial, summary }) {
    const [expanded, setExpanded] = useState(false);

    if (!trial) return null;

    const sections = [
        {
            icon: "🎯",
            label: "Purpose",
            text: summary?.purpose ||
                "This trial aims to evaluate the safety and efficacy of a new treatment approach for cancer patients.",
        },
        {
            icon: "👤",
            label: "Who Can Join",
            text: summary?.eligibility ||
                `Patients aged ${trial.minAge || "18"}–${trial.maxAge || "75"} with confirmed diagnosis. ${trial.gender !== "All" ? `${trial.gender} only.` : "All genders welcome."}`,
        },
        {
            icon: "💊",
            label: "Treatment",
            text: summary?.treatment ||
                (trial.interventions || "Treatment details available on ClinicalTrials.gov"),
        },
        {
            icon: "📍",
            label: "Location",
            text: trial.locations?.slice(0, 3).join(", ") || "Multiple locations",
        },
        {
            icon: "📅",
            label: "Timeline",
            text: `Started: ${trial.startDate || "N/A"} · Enrollment: ${trial.enrollment ? trial.enrollment + " patients" : "N/A"}`,
        },
    ];

    return (
        <div style={{
            background: "#FFFFFF",
            border: "1px solid #E2E8F0",
            borderRadius: 14,
            overflow: "hidden",
            marginTop: 12,
        }}>
            {/* Header */}
            <div style={{
                background: "linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)",
                padding: "14px 18px",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
            }}>
                <div style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                }}>
                    <span style={{ fontSize: 18 }}>🤖</span>
                    <div>
                        <div style={{
                            fontSize: 13,
                            fontWeight: 700,
                            color: "#FFFFFF",
                        }}>
                            AI Plain Language Summary
                        </div>
                        <div style={{
                            fontSize: 11,
                            color: "rgba(255,255,255,0.7)",
                        }}>
                            Generated by Claude AI — simplified for patients & doctors
                        </div>
                    </div>
                </div>
                <button
                    onClick={() => setExpanded(!expanded)}
                    style={{
                        padding: "5px 12px",
                        borderRadius: 8,
                        border: "1px solid rgba(255,255,255,0.3)",
                        background: "rgba(255,255,255,0.15)",
                        color: "#FFFFFF",
                        fontSize: 12,
                        fontWeight: 600,
                        cursor: "pointer",
                        fontFamily: "Inter, sans-serif",
                    }}
                >
                    {expanded ? "▲ Collapse" : "▼ Read Summary"}
                </button>
            </div>

            {/* Content */}
            {expanded && (
                <div style={{ padding: 18 }}>
                    {/* Trial title */}
                    <div style={{
                        fontSize: 14,
                        fontWeight: 700,
                        color: "#1E293B",
                        marginBottom: 16,
                        lineHeight: 1.4,
                    }}>
                        {trial.title || trial.briefTitle}
                    </div>

                    {/* Sections */}
                    <div style={{
                        display: "grid",
                        gridTemplateColumns: "1fr 1fr",
                        gap: 10,
                        marginBottom: 14,
                    }}>
                        {sections.map((s, i) => (
                            <div key={i} style={{
                                padding: "10px 14px",
                                background: "#F8FAFF",
                                borderRadius: 10,
                                border: "1px solid #EEF2FF",
                            }}>
                                <div style={{
                                    display: "flex",
                                    alignItems: "center",
                                    gap: 6,
                                    marginBottom: 5,
                                }}>
                                    <span style={{ fontSize: 14 }}>{s.icon}</span>
                                    <span style={{
                                        fontSize: 11,
                                        fontWeight: 700,
                                        color: "#6366F1",
                                        textTransform: "uppercase",
                                        letterSpacing: "0.04em",
                                    }}>
                                        {s.label}
                                    </span>
                                </div>
                                <p style={{
                                    fontSize: 12.5,
                                    color: "#374151",
                                    lineHeight: 1.5,
                                    margin: 0,
                                }}>
                                    {s.text}
                                </p>
                            </div>
                        ))}
                    </div>

                    {/* Sponsor */}
                    <div style={{
                        display: "flex",
                        alignItems: "center",
                        gap: 8,
                        padding: "8px 12px",
                        background: "#F1F5F9",
                        borderRadius: 8,
                        fontSize: 12,
                        color: "#64748B",
                    }}>
                        <span>🏥</span>
                        <span>
                            <strong>Sponsor:</strong> {trial.sponsor || "N/A"}
                        </span>
                        <span style={{ margin: "0 4px" }}>·</span>
                        <a
                            href={trial.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{
                                color: "#6366F1",
                                fontWeight: 600,
                                textDecoration: "none",
                            }}
                        >
                            View on ClinicalTrials.gov →
                        </a>
                    </div>
                </div>
            )
            }
        </div >
    );
}